name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master  # or "main" if your default branch is "main"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/frontend  # Important because your frontend is in a subfolder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g gh-pages
          npm run deploy
